{% set name = "msal_extensions" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/archive/{{ version }}.tar.gz
  sha256: 47929517fae427695bafb5e8fccd4addd2025bf24b5ce2776cb4dc9f348a71f4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - msal >=0.4.1,<2.0
    - portalocker

test:
  imports:
    - msal_extensions

about:
  home: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Microsoft Authentication extensions for MSAL.Python '
  description: |
    Microsoft Authentication extensions for MSAL.Python 
  doc_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  dev_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python

extra:
  recipe-maintainers:
    - roederja2
