{% set name = "msal_extensions" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/archive/{{ version }}.tar.gz
  sha256: 09197b364a665ca043cd9552fafa0d78c3c6153248ce5c6fd74e60cae4636d11

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - msal >=0.4.1,<2.0
    - portalocker
    - pathlib2  # [py2k]

test:
  imports:
    - msal_extensions

about:
  home: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Microsoft Authentication extensions for MSAL.Python '
  description: |
    Microsoft Authentication extensions for MSAL.Python 
  doc_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  dev_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python

extra:
  recipe-maintainers:
    - roederja2
