{% set name = "msal_extensions" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/archive/{{ version }}.tar.gz
  sha256: c8032459d8396a8d8992a0625a35b4ef44c2d784b2efddabb042f3e6cafb2dc4

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - libsecret  # [not win]
    - msal >=1.29,<2.0
    - portalocker >=1.6,<3.0
    - pygobject >=3,<4  # [not win]

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - msal_extensions
  commands:
    - pip check

about:
  home: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Microsoft Authentication extensions for MSAL.Python '
  description: |
    Microsoft Authentication extensions for MSAL.Python 
  doc_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python
  dev_url: https://github.com/AzureAD/microsoft-authentication-extensions-for-python

extra:
  recipe-maintainers:
    - dhirschfeld
    - roederja
